// src/lib/components/Meta.svelte
<script lang="ts">
  import { CMS_NAME, CMS_DESC, HOME_OG_IMAGE_URL, HOME_TW_IMAGE_URL } from '$lib/constants';
  import { page } from '$app/stores'; // To get the current path for canonical URL

  export let title: string = `${CMS_NAME} - ${CMS_DESC}`; // Default title
  export let description: string = `@{Nagatani}が雑にいろいろ書くブログ`; // Default description from original twitter:description
  export let image: string = HOME_OG_IMAGE_URL; // Default OG image
  export let twitterImage: string = HOME_TW_IMAGE_URL; // Default Twitter image
  // Canonical URL should be the full URL of the current page
  $: canonicalUrl = $page.url.href;

  // Note: Favicon links, theme-color, and other static head elements
  // are recommended to be in app.html or the root +layout.svelte for SvelteKit.
  // This component will focus on page-specific meta tags.
</script>

<svelte:head>
  <title>{title}</title>
  <meta name="description" content={description} />

  <!-- Open Graph -->
  <meta property="og:type" content="website" />
  <meta property="og:title" content={title} />
  <meta property="og:description" content={description} />
  <meta property="og:image" content={$page.url.origin + image} />
  <meta property="og:url" content={canonicalUrl} />
  <meta property="og:site_name" content={CMS_NAME} />

  <!-- Twitter Card -->
  <meta name="twitter:card" content="summary_large_image" />
  <!-- summary_large_image is often preferred over summary -->
  <meta name="twitter:site" content="@Nagatani" />
  <meta name="twitter:creator" content="@Nagatani" /> <!-- Assuming creator is the same as site -->
  <meta name="twitter:title" content={title} />
  <meta name="twitter:description" content={description} />
  <meta name="twitter:image" content={$page.url.origin + twitterImage} />

  <link rel="canonical" href={canonicalUrl} />
</svelte:head>

// components/meta.tsx
import Head from 'next/head'
import { CMS_NAME, CMS_DESC, HOME_OG_IMAGE_URL, HOME_TW_IMAGE_URL } from '../lib/constants'

const Meta = () => {
  return (
    <Head>
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="/favicon/apple-touch-icon.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/favicon/favicon-32x32.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/favicon/favicon-16x16.png"
      />
      <link rel="manifest" href="/favicon/site.webmanifest" />
      <link
        rel="mask-icon"
        href="/favicon/safari-pinned-tab.svg"
        color="#000000"
      />
      <link rel="shortcut icon" href="/favicon/favicon.ico" />
      <meta name="msapplication-TileColor" content="#000000" />
      <meta name="msapplication-config" content="/favicon/browserconfig.xml" />
      <meta name="theme-color" content="#000" />
      <link rel="alternate" type="application/rss+xml" href="/feed.xml" />
      <meta
        name="description"
        content={`${CMS_NAME} - ${CMS_DESC}`}
      />
      <meta property="og:image" content={HOME_OG_IMAGE_URL} />
      <meta name="twitter:card" content="summary" />
      <meta name="twitter:site" content="@Nagatani" />
      <meta name="twitter:title" content={`${CMS_NAME} - ${CMS_DESC}`} />
      <meta name="twitter:description" content={`@Nagataniが雑にいろいろ書くブログ`} />
      <meta name="twitter:image" content={HOME_TW_IMAGE_URL} />
    </Head>
  )
}

export default Meta
